<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<style>
#homecontent {
	background: url("images/content-bg.png") repeat-x scroll 0 0 #FAFAFA;
	position: relative;
}

#homecontent-mid {
	background: url("images/bg-stage.png") repeat-y scroll right top #FFFFFF;
	min-height: 100%;
	outline: medium none;
	top: -40px;
}

#homebanner {
	background: url("images/bg-stage-shade.png") repeat-x scroll 0 0
		transparent;
	padding-right: 20px;
	position: relative;
}

.rounded {
	border-radius: 10px 10px 10px 10px;
}

.sliderdiv {
	background: none repeat scroll 0 0 FFFFFF;
	float: left;
}

.main-search {
	background: none repeat scroll 0 0 #FFFFFF;
	float: left;
	overflow: hidden;
}

.nav-buttons {
	background: none repeat scroll 0 0 #FFFFFF;
	float: left;
	overflow: hidden;
}

</style>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" />
<link href="http://fonts.googleapis.com/css?family=Droid+Sans:400,700"
	rel="stylesheet" type="text/css">

<?php
require_once('views/helpers/ScriptContainer.php');
print ScriptContainer::$instance->renderCSSHead();
print ScriptContainer::$instance->renderJSHead();
?>


      <link rel="stylesheet" type="text/css"
	href="https://google-developers.appspot.---com/_static/f7a896e076/css/screen-docs.css" />
<link rel="stylesheet"
	href="//www.google.com/cse/style/look/default.css" type="text/css" />
<link rel="stylesheet"
	href="//fonts.googleapis.com/css?family=Open+Sans:300,400"
	type="text/css">
<script
	src="https://google-developers.appspot.com/_static/f7a896e076/js/prettify-bundle.js"></script>

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.min.js"></script>
<script id="jqueryui"
	src="//ajax.googleapis.com/ajax/libs/jqueryui/1.9.2/jquery-ui.min.js"
	defer async></script>
<script
	src="//www.google.com/jsapi?key=AIzaSyCZfHRnq7tigC-COeQRmoa9Cxr0vbrK6xw"></script>
<!--[if lt IE 9]>
    <script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
<script
	src="https://google-developers.appspot.com/_static/f7a896e076/js/framebox.js"></script>

<script>
  $(function() {
    $( "#accordion" ).accordion({header: "h3", collapsible: true,active: 2})
  });
  </script>

</head>
<body class="yui-skin-sam">

	<div id="pageHolder">

		<div id="header"><?php require_once('views/scripts/header.phtml');?></div>
		<div id="content">

			<!-------   /////////////////////////// get data ////////////////////// -->

			<div>

				<?php  //require_once('views/scripts/dashboard/load_data.phtml');?>



			<!-------   /////////////////////////// make top buttons ////////////////////// -->

			<div class="rightdiv" style="float: right;">
				<?php  
                                    $singleSelection = true;
                                    require_once('views/scripts/dashboard/top_buttons.phtml');
                                ?>
					
			</div>



			<!-------   /////////////////////////// make left buttons ////////////////////// -->

			<div class="nav-buttons">
				<?php  
                                    $fileInfo = pathinfo(__FILE__);
                                    $fileID = $fileInfo['filename'];
                                    require_once('views/scripts/dashboard/left_buttons.phtml');
                                ?>				
			</div>
			
			<!-------   /////////////////////////// load scripts ////////////////////// -->
            <div class="nav-buttons">
				<?php //require_once('views/scripts/dashboard/displayScripts.phtml');?>
			</div>

			<!-------   /////////////////////////// charts ////////////////////// -->


			<body class="docs slim framebox_body">

				<div id="allCharts" class="container">
				<div id="toprow" class="container">
						<div id="homecontent" class="container">
							<div id="homecontent-mid" class="row rounded">
								<div id="homebanner" class="rounded">
								<div class="sliderdiv">
                                                                        <div id="infobutton" class="infobutton hidden">
                                                                                <span class="infowrap"><i class="fa fa-info-circle"></i></span>
                                                                                <div id="" class="infodiv" >
                                                                                    This chart shows stock out rates over time at facilities that have provided 
                                                                                    any FP services or implants specifically in the past. <br/><br/>
                                                                                    
                                                                                    For FP, this is the percentage of facilities reporting in the given month that 
                                                                                    have provided any FP commodities any time in the last six months that were 
                                                                                    stocked out of any FP commodity for at least seven days in the given month. <br/><br/>
                                                                                    
                                                                                    For implants, this is the percentage of facilities reporting in the given month that 
                                                                                    have consumed implants any time in the last six months that are stocked out of 
                                                                                    implants in the given month.
                                                                                </div>
                                                                            </div>
									<div id="chart11_div" style="width: 700px; height: 300px;"></div>
									</div>
									<div class="main-search">
										<div id="chart12_div" style="width: 700px; height: 300px;"></div>
									</div>
								</div>
							</div>
						</div>			
					</div>

				<div class="clear"></div>
				<div class="hrGrey"></div>
				<div class="clear"></div>

				

								<!-------   /////////////////////////// chart 2,1 ////////////////////// -->
								
					<div id="bottomrow" class="container">
						<div id="homecontent" class="container">
							<div id="homecontent-mid" class="row rounded">
								<div id="homebanner" class="rounded">
								<div class="sliderdiv">
									<div id="chart13_div" style="width: 800px; height: 300px;"></div>
									</div>
									<div class="main-search">
										<div id="chart14_div" style="width: 500px; height: 300px;"></div>
									</div>
								</div>
							</div>
						</div>
								
								<!-------   /////////////////////////// chart 2,2 ////////////////////// -->
								
								
								<div class="main-search"></div>

					</div>
				</div>
		
	</div>

		<div class="clear"></div>
		<div class="hrGrey"></div>
		<div class="clear"></div>
		
		<script type="text/javascript" src="https://www.google.com/jsapi"></script>

		<!-------   /////////////////////////// main gnr ////////////////////// -->

		<script type="text/javascript">
		
  google.load('visualization', '1.1', {'packages':['corechart', 'table', 'gauge', 'controls']});
  google.load('visualization', '1.1', {'packages':['bar']});
  google.setOnLoadCallback(apiLoaded);
  function apiLoaded() {
	  document.getElementById("allCharts").style.marginLeft="130px";

	drawChart11();
	//drawChart12();
		
	var currentLevel;
	currentLevel = <?php echo '\'' . $this->location_data[0]['name'] . '\''; ?>;

<?php  //file_put_contents('c:\wamp\logs\php_debug.log', 'dash3 193 >'.PHP_EOL, FILE_APPEND | LOCK_EX);	ob_start();
	   //var_dump("location_data=", $this->location_data[0],"END");
	   //var_dump("facility_data=",$this->facility_data[0],"END");
	   //$result = ob_get_clean(); file_put_contents('c:\wamp\logs\php_debug.log', $result .PHP_EOL, FILE_APPEND | LOCK_EX); 
?>
		 
  }

  <!-------   /////////////////////////// script 1,1 ////////////////////// -->

  //TA:17:18 Stock outs charts
  function drawChart11() {
	  
        var chart11Data = google.visualization.arrayToDataTable([
        ['Month', 
         '% FP facilities stocked out of any FP commodity for 7 days', 
         { role: 'tooltip', type: 'string', 'p': {'html': true} },
         '% implant facilities stocked out of implants',
     { role: 'tooltip', type: 'string', 'p': {'html': true} },],

                            
               <?php 
                    //$locationNamesArray = explode(',', $locationNames);

//                    if(!empty($this->facs_providing_stockedout)){
//                        foreach ($this->facs_providing_stockedout as $key=>$monthProviders){ 
//                            $month = $monthProviders['month'];
//                            $seven_days_percent = round($monthProviders['seven_days_percent'] * 100,2);
//                            $implant_percent = round($monthProviders['implant_percent'] * 100,2);
                    ?>
                            //[<?php //echo "'$month', $seven_days_percent, $implant_percent"; ?>],

                    <?php
                         //   }//end foreach
                        //} //end if
                    ?>
                    
                    <?php 
                    //$locationNamesArray = explode(',', $locationNames);

                    if(!empty($this->fp_facs_providing_stockedout)){
                        foreach ($this->fp_facs_providing_stockedout as $key=>$monthProviders){ 
                            $month = $monthProviders['month'];
                            
                            $seven_days_percent = round($monthProviders['seven_days_percent'] * 100,1);
                            $seven_days_percentToolTip = "<p style=\"padding:5px 7px;\"><b>$month</b><br/>Percent of FP facilities stocked out of any FP commodity for 7 days:</b> " . $seven_days_percent . "\%</p>";
                            
                            $implant_percent = round($this->larc_facs_providing_stockedout[$key]['implant_percent'] * 100,1);
                            $implant_percentToolTip = "<p style=\"padding:5px 7px;\"><b>$month</b><br/>Percent of implant facilities stocked out of implants:</b> " . $implant_percent . "\%</p>";
                            ?>
                            [<?php echo "'$month', $seven_days_percent,'$seven_days_percentToolTip', $implant_percent,'$implant_percentToolTip'"; ?>],

                    <?php
                            }//end foreach
                        } //end if
                    ?>
        ]);

             <?php 
                    if($this->freshvisit)
                        echo  " var title_data = 'Stock outs, $this->start_date to $this->end_date' " ;
                    else
                        echo  " var title_data = 'Stock outs for $this->location_name, $this->start_date to $this->end_date' " ;
              ?>
             <?php //echo  " var title_data = 'Stock Outs, " . $this->start_date . " to " . $this->end_date ."' " ?>;

              var chart11Options = {
                title: title_data,
                titleTextStyle: { fontSize: 16 },
                vAxis: {format: '#\'%\'', minValue: 4},
                chartArea: {width: '90%', left: 60},//new
                tooltip : {isHtml : true },
                legend: {textStyle: {'margin-bottom': '100px', 'margin-top': '100px'}, position: 'bottom'}
              };

              var chart11 = new google.visualization.LineChart(document.getElementById('chart11_div'));

              //show info icon
                google.visualization.events.addListener(chart11, 'ready', function(){
                       $("#chart11_div").siblings('#infobutton').removeClass('hidden');
                });
                
              chart11.draw(chart11Data, chart11Options);
}

  

</script>


<script>
  devsite.github.Link.convertAnchors();
  window.prettyPrint();
</script>	

  <div id="footer"><?php require_once('views/scripts/footer.phtml');?></div>

</body>

</html>